package constants

var DefaultExclusions = []string{
	`hiberfil.sys`,
	`pagefile.sys`,
	`swapfile.sys`,
	`autoexec.bat`,
	`Config.Msi`,
	`Documents and Settings`,
	`Recycled`,
	`Recycler`,
	`$$Recycle.Bin`,
	`Recovery`,
	`Program Files`,
	`Program Files (x86)`,
	`ProgramData`,
	`PerfLogs`,
	`Windows`,
	`Windows.old`,
	`$$WINDOWS.~BT`,
	`$$WinREAgent`,
	`$RECYCLE.BIN`,
	`$WinREAgent`,
	`System Volume Information`,
	`Temporary Internet Files`,
	`Microsoft/Windows/Recent`,
	`Microsoft/**/RecoveryStore`,
	`Microsoft/**/Windows/**/*.edb`,
	`Microsoft/**/Windows/**/*.log`,
	`Microsoft/**/Windows/Cookies*`,
	`Microsoft/**/Logs*`,
	`Users/Public/AccountPictures`,
	`I386`,
	`Internet Explorer`,
	`MSOCache`,
	`NTUSER*`,
	`UsrClass.dat`,
	`Thumbs.db`,
	`AppData/Local/Temp*`,
	`AppData/Temp*`,
	`Local Settings/Temp*`,
	`**.tmp`,
	`AppData/**/*cache*`,
	`AppData/**/Crash Reports`,
	`AppData/Local/Apple Computer/Mobile Sync`,
	`AppData/Local/Comms/UnistoreDB`,
	`AppData/Local/ElevatedDiagnostics`,
	`AppData/Local/Microsoft/Windows/Explorer`,
	`AppData/Local/Microsoft/Windows/INetCache`,
	`AppData/Local/Microsoft/Windows/UPPS`,
	`AppData/Local/Microsoft/Windows/WebCache`,
	`AppData/Local/Microsoft/Windows Store`,
	`AppData/Local/Packages`,
	`Application Data/Apple Computer/Mobile Sync`,
	`Application Data/Application Data*`,
	`iPhoto Library/iPod Photo Cache`,
	`cookies.sqlite-*`,
	`permissions.sqlite-*`,
	`Local Settings/History`,
	`OneDrive/.849C9593-D756-4E56-8D6E-42412F2A707B`,
}
